i-kijiji/urls.py
from django.conf.urls.defaults import *
from django.contrib import admin


urlpatterns = patterns('',
	url(r'^$', 'i-kijiji.views.welcome'),
	url(r'^sitelist/$', 'i-kijiji.views.site_list'),
	url(r'^selectsite/$', 'i-kijiji.views.region_list'),
	url(r'^selectvillage/$', 'i-kijiji.views.v_region_list'),
	url(r'^northern/$', 'i-kijiji.views.northern_list'),
	url(r'^v_northern/$', 'i-kijiji.views.v_northern_list'),
	url(r'^uer/$', 'i-kijiji.views.uer_list'),
	url(r'^v_uer/$', 'i-kijiji.views.v_uer_list'),
	url(r'^uwr/$', 'i-kijiji.views.uwr_list'),
	url(r'^v_uwr/$', 'i-kijiji.views.v_uwr_list'),
	url(r'^volta/$', 'i-kijiji.views.volta_list'),
	url(r'^v_volta/$', 'i-kijiji.views.v_volta_list'),
	url(r'^ga/$', 'i-kijiji.views.ga_list'),
	url(r'^v_ga/$', 'i-kijiji.views.v_ga_list'),
	url(r'^ba/$', 'i-kijiji.views.ba_list'),
	url(r'^v_ba/$', 'i-kijiji.views.v_ba_list'),
	url(r'^ashanti/$', 'i-kijiji.views.ashanti_list'),
	url(r'^v_ashanti/$', 'i-kijiji.views.v_ashanti_list'),
	url(r'^eastern/$', 'i-kijiji.views.eastern_list'),
	url(r'^v_eastern/$', 'i-kijiji.views.v_eastern_list'),
	url(r'^western/$', 'i-kijiji.views.western_list'),
	url(r'^v_western/$', 'i-kijiji.views.v_western_list'),
	url(r'^central/$', 'i-kijiji.views.central_list'),
	url(r'^v_central/$', 'i-kijiji.views.v_central_list'),

	url(r'^sitedetail/(?P<id>\d+)/$','i-kijiji.views.site_detail'),
	url(r'^villagedetail/(?P<id>\d+)/$','i-kijiji.views.village_detail'),
	
	url(r'^reviewsite/(?P<id>\d+)/((?P<showReviews>.*)/)?$','i-kijiji.views.detail_review'),
	url(r'^login/$', 'i-kijiji.views.login'),	
	url(r'^register/$', 'i-kijiji.views.register'),
	url(r'^welcome/$', 'i-kijiji.views.welcome'),
	url(r'^myvillage/$', 'i-kijiji.views.my_village'),
	url(r'^features/$', 'i-kijiji.views.feature_list'),
)

urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'i-kijiji.views.login', name='home'),
    # url(r'^Tourist/', include('Tourist.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i-kijiji/', include('i-kijiji.urls')),
    url(r'^users/', include('users.urls')),
    (r'^accounts/', include('registration.backends.default.urls')),
)

i-kijiji/models.py
from django.contrib import admin

from django.db import models



class TouristSite(models.Model):
	name= models.CharField(max_length=200)
	town= models.CharField(max_length=200)
	country= models.CharField(max_length=200)
	last_modified= models.DateTimeField(auto_now=True)
	SITE_CHOICES=(('hotel', 'Hotel'), ('park', 'Park'), ('forest_reserve', 'Forest Reserve'), ('wetland', 'Wetland'), ('heritage_site', 'Heritage Site'),('castle','Fort/Castle'),('museum', 'Museum'))
	site_type=models.CharField(max_length=60, choices=SITE_CHOICES)
	REGION_CHOICES=(('greater_accra', 'Greater Accra'), ('northern', 'Northern'), ('brong_ahafo', 'Brong Ahafo'),
	('central', 'Central'), ('upper_east', 'Upper East'),
	('upper_west','Upper West'),('ashanti', 'Ashanti'),('volta','Volta'),('western', 'Western'),('eastern', 'Eastern'))
	region= models.CharField(max_length=60, choices=REGION_CHOICES)
	
	COUNTRIES = (
    ('AFG', ('Afghanistan')), 
    ('ALA', ('Aland Islands')),
    ('ALB', ('Albania')),
    ('DZA', ('Algeria')),
    ('ASM', ('American Samoa')),
    ('AND', ('Andorra')),
    ('AGO', ('Angola')),
    ('AIA', ('Anguilla')),
    ('ATG', ('Antigua and Barbuda')),
    ('ARG', ('Argentina')),
    ('ARM', ('Armenia')),
    ('ABW', ('Aruba')),
    ('AUS', ('Australia')),
    ('AUT', ('Austria')),
    ('AZE', ('Azerbaijan')),
    ('BHS', ('Bahamas')),
    ('BHR', ('Bahrain')),
    ('BGD', ('Bangladesh')),
    ('BRB', ('Barbados')),
    ('BLR', ('Belarus')),
    ('BEL', ('Belgium')),
    ('BLZ', ('Belize')),
    ('BEN', ('Benin')),
    ('BMU', ('Bermuda')),
    ('BTN', ('Bhutan')),
    ('BOL', ('Bolivia')),
    ('BIH', ('Bosnia and Herzegovina')),
    ('BWA', ('Botswana')),
    ('BRA', ('Brazil')),
    ('VGB', ('British Virgin Islands')),
    ('BRN', ('Brunei Darussalam')),
    ('BGR', ('Bulgaria')),
    ('BFA', ('Burkina Faso')),
    ('BDI', ('Burundi')),
    ('KHM', ('Cambodia')),
    ('CMR', ('Cameroon')),
    ('CAN', ('Canada')),
    ('CPV', ('Cape Verde')),
    ('CYM', ('Cayman Islands')),
    ('CAF', ('Central African Republic')),
    ('TCD', ('Chad')),
    ('CIL', ('Channel Islands')),
    ('CHL', ('Chile')),
    ('CHN', ('China')),
    ('HKG', ('China - Hong Kong')),
    ('MAC', ('China - Macao')),
    ('COL', ('Colombia')),
    ('COM', ('Comoros')),
    ('COG', ('Congo')),
    ('COK', ('Cook Islands')),
    ('CRI', ('Costa Rica')),
    ('CIV', ('Cote d\'Ivoire')),
    ('HRV', ('Croatia')),
    ('CUB', ('Cuba')),
    ('CYP', ('Cyprus')),
    ('CZE', ('Czech Republic')),
    ('PRK', ('Democratic People\'s Republic of Korea')),
    ('COD', ('Democratic Republic of the Congo')),
    ('DNK', ('Denmark')),
    ('DJI', ('Djibouti')),
    ('DMA', ('Dominica')),
    ('DOM', ('Dominican Republic')),
    ('ECU', ('Ecuador')),
    ('EGY', ('Egypt')),
    ('SLV', ('El Salvador')),
    ('GNQ', ('Equatorial Guinea')),
    ('ERI', ('Eritrea')),
    ('EST', ('Estonia')),
    ('ETH', ('Ethiopia')),
    ('FRO', ('Faeroe Islands')),
    ('FLK', ('Falkland Islands (Malvinas)')),
    ('FJI', ('Fiji')),
    ('FIN', ('Finland')),
    ('FRA', ('France')),
    ('GUF', ('French Guiana')),
    ('PYF', ('French Polynesia')),
    ('GAB', ('Gabon')),
    ('GMB', ('Gambia')),
    ('GEO', ('Georgia')),
    ('DEU', ('Germany')),
    ('GHA', ('Ghana')),
    ('GIB', ('Gibraltar')),
    ('GRC', ('Greece')),
    ('GRL', ('Greenland')),
    ('GRD', ('Grenada')),
    ('GLP', ('Guadeloupe')),
    ('GUM', ('Guam')),
    ('GTM', ('Guatemala')),
    ('GGY', ('Guernsey')),
    ('GIN', ('Guinea')),
    ('GNB', ('Guinea-Bissau')),
    ('GUY', ('Guyana')),
    ('HTI', ('Haiti')),
    ('VAT', ('Holy See (Vatican City)')),
    ('HND', ('Honduras')),
    ('HUN', ('Hungary')),
    ('ISL', ('Iceland')),
    ('IND', ('India')),
    ('IDN', ('Indonesia')),
    ('IRN', ('Iran')),
    ('IRQ', ('Iraq')),
    ('IRL', ('Ireland')),
    ('IMN', ('Isle of Man')),
    ('ISR', ('Israel')),
    ('ITA', ('Italy')),
    ('JAM', ('Jamaica')),
    ('JPN', ('Japan')),
    ('JEY', ('Jersey')),
    ('JOR', ('Jordan')),
    ('KAZ', ('Kazakhstan')),
    ('KEN', ('Kenya')),
    ('KIR', ('Kiribati')),
    ('KWT', ('Kuwait')),
    ('KGZ', ('Kyrgyzstan')),
    ('LAO', ('Lao People\'s Democratic Republic')),
    ('LVA', ('Latvia')),
    ('LBN', ('Lebanon')),
    ('LSO', ('Lesotho')),
    ('LBR', ('Liberia')),
    ('LBY', ('Libyan Arab Jamahiriya')),
    ('LIE', ('Liechtenstein')),
    ('LTU', ('Lithuania')),
    ('LUX', ('Luxembourg')),
    ('MKD', ('Macedonia')),
    ('MDG', ('Madagascar')),
    ('MWI', ('Malawi')),
    ('MYS', ('Malaysia')),
    ('MDV', ('Maldives')),
    ('MLI', ('Mali')),
    ('MLT', ('Malta')),
    ('MHL', ('Marshall Islands')),
    ('MTQ', ('Martinique')),
    ('MRT', ('Mauritania')),
    ('MUS', ('Mauritius')),
    ('MYT', ('Mayotte')),
    ('MEX', ('Mexico')),
    ('FSM', ('Micronesia, Federated States of')),
    ('MCO', ('Monaco')),
    ('MNG', ('Mongolia')),
    ('MNE', ('Montenegro')),
    ('MSR', ('Montserrat')),
    ('MAR', ('Morocco')),
    ('MOZ', ('Mozambique')),
    ('MMR', ('Myanmar')),
    ('NAM', ('Namibia')),
    ('NRU', ('Nauru')),
    ('NPL', ('Nepal')),
    ('NLD', ('Netherlands')),
    ('ANT', ('Netherlands Antilles')),
    ('NCL', ('New Caledonia')),
    ('NZL', ('New Zealand')),
    ('NIC', ('Nicaragua')),
    ('NER', ('Niger')),
    ('NGA', ('Nigeria')),
    ('NIU', ('Niue')),
    ('NFK', ('Norfolk Island')),
    ('MNP', ('Northern Mariana Islands')),
    ('NOR', ('Norway')),
    ('PSE', ('Occupied Palestinian Territory')),
    ('OMN', ('Oman')),
    ('PAK', ('Pakistan')),
    ('PLW', ('Palau')),
    ('PAN', ('Panama')),
    ('PNG', ('Papua New Guinea')),
    ('PRY', ('Paraguay')),
    ('PER', ('Peru')),
    ('PHL', ('Philippines')),
    ('PCN', ('Pitcairn')),
    ('POL', ('Poland')),
    ('PRT', ('Portugal')),
    ('PRI', ('Puerto Rico')),
    ('QAT', ('Qatar')),
    ('KOR', ('Republic of Korea')),
    ('MDA', ('Republic of Moldova')),
    ('REU', ('Reunion')),
    ('ROU', ('Romania')),
    ('RUS', ('Russian Federation')),
    ('RWA', ('Rwanda')),
    ('BLM', ('Saint-Barthelemy')),
    ('SHN', ('Saint Helena')),
    ('KNA', ('Saint Kitts and Nevis')),
    ('LCA', ('Saint Lucia')),
    ('MAF', ('Saint-Martin (French part)')),
    ('SPM', ('Saint Pierre and Miquelon')),
    ('VCT', ('Saint Vincent and the Grenadines')),
    ('WSM', ('Samoa')),
    ('SMR', ('San Marino')),
    ('STP', ('Sao Tome and Principe')),
    ('SAU', ('Saudi Arabia')),
    ('SEN', ('Senegal')),
    ('SRB', ('Serbia')),
    ('SYC', ('Seychelles')),
    ('SLE', ('Sierra Leone')),
    ('SGP', ('Singapore')),
    ('SVK', ('Slovakia')),
    ('SVN', ('Slovenia')),
    ('SLB', ('Solomon Islands')),
    ('SOM', ('Somalia')),
    ('ZAF', ('South Africa')),
    ('ssd', ('South Sudan')),
    ('ESP', ('Spain')),
    ('LKA', ('Sri Lanka')),
    ('SDN', ('Sudan')),
    ('SUR', ('Suriname')),
    ('SJM', ('Svalbard and Jan Mayen Islands')),
    ('SWZ', ('Swaziland')),
    ('SWE', ('Sweden')),
    ('CHE', ('Switzerland')),
    ('SYR', ('Syrian Arab Republic')),
    ('TJK', ('Tajikistan')),
    ('THA', ('Thailand')),
    ('TLS', ('Timor-Leste')),
    ('TGO', ('Togo')),
    ('TKL', ('Tokelau')),
    ('TON', ('Tonga')),
    ('TTO', ('Trinidad and Tobago')),
    ('TUN', ('Tunisia')),
    ('TUR', ('Turkey')),
    ('TKM', ('Turkmenistan')),
    ('TCA', ('Turks and Caicos Islands')),
    ('TUV', ('Tuvalu')),
    ('UGA', ('Uganda')),
    ('UKR', ('Ukraine')),
    ('ARE', ('United Arab Emirates')),
    ('GBR', ('United Kingdom')),
    ('TZA', ('United Republic of Tanzania')),
    ('USA', ('United States of America')),
    ('VIR', ('United States Virgin Islands')),
    ('URY', ('Uruguay')),
    ('UZB', ('Uzbekistan')),
    ('VUT', ('Vanuatu')),
    ('VEN', ('Venezuela (Bolivarian Republic of)')),
    ('VNM', ('Viet Nam')),
    ('WLF', ('Wallis and Futuna Islands')),
    ('ESH', ('Western Sahara')),
    ('YEM', ('Yemen')),
    ('ZMB', ('Zambia')),
    ('ZWE', ('Zimbabwe')),
)
	country = models.CharField(max_length=60, choices=COUNTRIES)
	def __unicode__(self):
		return self.name


class Review(models.Model):
	review_title = models.ForeignKey('TouristSite')
	review_body= models.TextField('')
	review_author= models.CharField(max_length=60)
	review_created= models.DateTimeField(auto_now=True)
	review_updated= models.DateTimeField(auto_now_add=True)
	def title_first_ten(self):
		return self.title[:10]
        def __unicode__(self):
		return self.review_author
	
class MyVillage(models.Model):
	v_name= models.CharField('Village name', max_length=30)
	v_region= models.CharField('Region', max_length=30)
	v_nearto= models.CharField('Nearest city/town', max_length=30)
	v_attraction1= models.CharField('Attraction 1', blank=True, max_length=50)
	v_attraction2= models.CharField('Attraction 2', blank=True, max_length=50)
	v_attraction3= models.CharField('Attraction 3', blank=True, max_length=50)
	v_attraction4= models.CharField('Attraction 4', blank=True, max_length=50)
	v_attraction5= models.CharField('Attraction 5', blank=True, max_length=50)
	v_review= models.TextField('Village Review', blank=True, )
	v_added=models.DateTimeField('Date added', auto_now=True)
	v_updated=models.DateTimeField('Last updated', auto_now_add=True)
	REGION_CHOICES=(('greater_accra', 'Greater Accra'), ('northern', 'Northern'), ('brong_ahafo', 'Brong Ahafo'),
	('central', 'Central'), ('upper_east', 'Upper East'),
	('upper_west','Upper West'),('ashanti', 'Ashanti'),('volta','Volta'),('western', 'Western'),('eastern', 'Eastern'))
	v_region= models.CharField(max_length=60, choices=REGION_CHOICES)
	village_image = models.ImageField('Upload images', blank=True, upload_to='static')
	village_image_2 = models.ImageField('', blank=True, upload_to='static')
	village_image_3 = models.ImageField('', blank=True, upload_to='static')
	
	COUNTRIES = (
    ('AFG', ('Afghanistan')), 
    ('ALA', ('Aland Islands')),
    ('ALB', ('Albania')),
    ('DZA', ('Algeria')),
    ('ASM', ('American Samoa')),
    ('AND', ('Andorra')),
    ('AGO', ('Angola')),

templates/i-kijiji/ba.html
{% extends "i-kijiji/index.html" %}


{% block content %}
{% for site in ba_list %}

<a href="/i-kijiji/sitedetail/{{ site.id }}/"><ul>{{ site.name }}</ul></a>

{% endfor %}
{% endblock %}

templates/i-kijiji/features.html
{% extends "i-kijiji/index.html" %}
{% block content %}
hi there
{% for i in feature_list %}
<ul>{{ i.v_name }}</ul>
{% endfor %}
{% endblock %}

templates/i-kijiji/ga.html
{% extends "i-kijiji/index.html" %}
<div class="header">Hi there</div>
<p>Hi there!</p>

{% block content %}
{% for site in ga_list %}

<a href="/i-kijiji/sitedetail/{{ site.id }}/"><ul>{{ site.name }}</ul></a>

{% endfor %}
{% endblock %}
</p>
</body>
</html>

templates/i-kijiji/login.html
{% extends "i-kijiji/index.html" %}
 {% block content %}
<h1>i-Kijiji</h1>

<!-- Load FB JavaScript SDK -->

<script src="http://connect.facebook.net/en_US/all.js"></script>
      <script>
         FB.init({ 
            appId:'131672516919597', cookie:true, 
            status:true, xfbml:true 
         });
      </script>

<!-- Load FB Login -->

<script src="http://connect.facebook.net/en_US/all.js"></script>
      <script>
         FB.init({ 
            appId:'131672516919597', cookie:true, 
            status:true, xfbml:true 
         });
      </script>
<fb:login-button perms="email,user_checkins">Login with Facebook</fb:login-button>

{% endblock %}

templates/i-kijiji/myvillage.html
{% extends "i-kijiji/index.html" %}
{% block content %}
<p><table border="1" align="center">
<tr>
<td><ul>
<p>{{ my_village.name }}</p>
<p>{{ my_village.get_v_region_display }}</p>
<p>{{ my_village.nearto }}</p>
<p>{{ my_village.v_updated }}</p>
</ul></td>
<td width="450" height="400">
<div id="map" align ="center"><iframe width="425" height="350" frameborder="1" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?q=ghana&amp;hq=ghana&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;q=ghana&amp;&amp;hq=ghana&amp;style="color:#0000FF;text-align:left"><p>View Larger Map</p></a></small>
</div>
</td>
</tr>
</table></p>

<p><div align ="center">

<form method='post' action="" enctype="multipart/form-data">
{{ form }}
<input type='submit' name='Review' value='Post Review'>
</form>
</td>
</td>
</tr>


<!--
{% endblock %}

templates/i-kijiji/northern.html
{% extends "i-kijiji/index.html" %}
<div class="header">Hi there</div>


{% block content %}

{% for site in northern_list %}
<a href="/i-kijiji/sitedetail/{{ site.id }}/"><ul>{{ site.name }}</ul></a>


{% endfor %}
{% endblock %}

templates/i-kijiji/selectsite.html
{% extends "i-kijiji/index.html" %}
<div class="header">Hi there</div>
<p>Hi there!</p>

{% block content %}

<a href="/i-kijiji/ashanti"><ul>{{ ashanti.get_region_display }}</ul></a>
<a href="/i-kijiji/ba"><ul>{{ ba.get_region_display }}</ul></a>
<a href="/i-kijiji/eastern"><ul>{{ eastern.get_region_display }}</ul></a>
<a href="/i-kijiji/ga"><ul>{{ ga.get_region_display }}</ul></a>
<a href="/i-kijiji/northern"><ul>{{ northern.get_region_display }}</ul></a>
<a href="/i-kijiji/uer"><ul>{{ uer.get_region_display }}</ul></a>
<a href="/i-kijiji/uwr"><ul>{{ uwr.get_region_display }}</ul></a>
<a href="/i-kijiji/volta"><ul>{{ volta.get_region_display }}</ul></a>
<a href="/i-kijiji/western"><ul>{{ western.get_region_display }}</ul></a>



{% endblock %}
</p>
</body>
</html>

templates/i-kijiji/selectvillage.html
{% extends "i-kijiji/index.html" %}
<div class="header">Hi there</div>
<p>Hi there!</p>

{% block content %}

<a href="/i-kijiji/v_ashanti"><ul>{{ ashanti.get_v_region_display }}</ul></a>
<a href="/i-kijiji/v_ba"><ul>{{ ba.get_v_region_display }}</ul></a>
<a href="/i-kijiji/v_eastern"><ul>{{ eastern.get_v_region_display }}</ul></a>
<a href="/i-kijiji/v_ga"><ul>{{ ga.get_v_region_display }}</ul></a>
<a href="/i-kijiji/v_northern"><ul>{{ northern.get_v_region_display }}</ul></a>
<a href="/i-kijiji/v_uer"><ul>{{ uer.get_v_region_display }}</ul></a>
<a href="/i-kijiji/v_uwr"><ul>{{ uwr.get_v_region_display }}</ul></a>
<a href="/i-kijiji/v_volta"><ul>{{ volta.get_v_region_display }}</ul></a>
<a href="/i-kijiji/v_western"><ul>{{ western.get_v_region_display }}</ul></a>
<a href="/i-kijiji/v_central"><ul>{{ central.get_v_region_display }}</ul></a>



{% endblock %}
</p>
</body>
</html>

templates/i-kijiji/sitedetail.html
{% extends "i-kijiji/index.html" %}
{% block content %}
<p><table border="1" align="center">
<tr>
<td><ul>
<p>{{ site_detail.name }}</p>
<p>{{ site_detail.get_region_display }}</p>
<p>{{ site_detail.town }}</p>
<p>{{ site_detail.last_modified }}</p>
</ul></td>
<td width="450" height="400">
<div id="map" align ="center"><iframe width="425" height="350" frameborder="1" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?q={{ site.name }}+{{ site.town }}+{{ site.country }}&amp;hq={{ site.name }}+{{ site.town }}+{{ site.country }}&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;q={{ site.name }}+{{ site.town }}+{{ site.country }}&amp;&amp;hq={{ site.name }}+{{ site.town }}+{{ site.country }}&amp;style="color:#0000FF;text-align:left"><p>View Larger Map</p></a></small>
</div>
</td>

<td width="300" height="400">
<p align="center"><b>Write a Review</b></p>
<p><div align ="center"><form method='post' action="">
{{ form }}
<script typ="text/javascript">
function saythanks()
{
alert ("Thanks for the Review, journeymaker!");
}
</script>
<input type='submit' name='Submit' onclick="saythanks()">
</form></div></p>
</td>
</td>

</table></p>

<!--author's facebook image-->

<!-- Load FB Login -->

<script src="http://connect.facebook.net/en_US/all.js"></script>
      <script>
         FB.init({ 
            appId:'131672516919597', cookie:true, 
            status:true, xfbml:true 
         });
      </script>

<!-- Now the image -->

<script src="http://connect.facebook.net/en_US/all.js">
      </script>
      <script>
         FB.init({ 
            appId:'131672516919597', cookie:true, 
            status:true, xfbml:true 
         });
         FB.api('/me', function(user) {
           if(user != null) {
              var image = document.getElementById('image');
              image.src = 'https://graph.facebook.com/' + user.id + '/picture';
              var name = document.getElementById('name');
              name.innerHTML = user.name
           }
         });
       </script>
	<div align="left">
           
           

<br><br><br><br><br>
{% for item in review_items %}
<ul><b>Author:</b><i id="name"></i></b></ul>
<ul><img id="image" align="left"/>{{ item.review_body }}</ul>

{% endfor %}</p>

{% endblock %}

templates/i-kijiji/uer.html
{% extends "i-kijiji/index.html" %}
<div class="header">Hi there</div>
<p>Hi there!</p>

{% block content %}
{% for site in uer_list %}

<a href="/i-kijiji/sitedetail/{{ site.id }}/"><ul>{{ site.name }}</ul></a>

{% endfor %}
{% endblock %}
</p>
</body>
</html>

templates/i-kijiji/v_central.html
{% extends "i-kijiji/index.html" %}
<div class="header">Hi there</div>
<p>Hi there!</p>

{% block content %}
{% for site in v_central_list %}

<a href="/i-kijiji/villagedetail/{{ site.id }}/"><ul>{{ site.v_name }}</ul></a>

{% endfor %}
{% endblock %}
</p>
</body>
</html>

templates/i-kijiji/v_uer.html
{% extends "i-kijiji/index.html" %}
<div class="header">Hi there</div>
<p>Hi there!</p>

{% block content %}
{% for site in v_uer_list %}

<a href="/i-kijiji/villagedetail/{{ site.id }}/"><ul>{{ site.v_name }}</ul></a>

{% endfor %}
{% endblock %}
</p>
</body>
</html>

templates/i-kijiji/v_volta.html
{% extends "i-kijiji/index.html" %}
<div class="header">Hi there</div>
<p>Hi there!</p>

{% block content %}
{% for site in v_volta_list %}

<a href="/i-kijiji/villagedetail/{{ site.id }}/"><ul>{{ site.v_name }}</ul></a>

{% endfor %}
{% endblock %}
</p>
</body>
</html>

templates/i-kijiji/welcome.html
{% extends "i-kijiji/index.html" %}
{% block content %}

<!--<h2 id="titlebar">Welcome to i-Kijiji <br>Your village on the web</h2>-->

<div id="banner" align ="center" class="gmap">
</div>

<table border="0" class="menubar"><tr><div align="center">
<td class="menuitem">Home</td>
<td class="menuitem">Villages</td>
<td class="menuitem">Villagers</td>
<td class="menuitem">Reviews</td>
<td class="menuitem">Must Visit</td>
</div></tr>
</table>
<table class="contenttable" border="1">
<tr>
<td class="contentflank">
<p><a href ="/users/login">Login</a> or <a href="/accounts/register">Register</a></p>
<p><a href ="/i-kijiji/myvillage">Submit your village</a></p>
<a href ="/i-kijiji/selectvillage"><p>Go to Villages</p></a>
<a href ="/i-kijiji/selectsite"><p>See Attractions</p></a>

</td>
<td class="flash">
<div id="map" align ="center"><iframe class="gmap" frameborder="1" scrolling="no" marginheight="0" marginwidth="0" src="http://maps.google.com/maps?q=ghana&amp;hq=ghana&amp;output=embed"></iframe><br /><small><a href="http://maps.google.com/maps?f=q&amp;source=embed&amp;hl=en&amp;q=ghana&amp;&amp;hq=ghana&amp;style="
color:#0000FF;text-align:left></a></small></div>
</td>
<td class="contentflank">
<p>i-Kijiji is the largest online community of villagers in the world.</p>
<input class="joinusbutton" type="submit" value="JOIN NOW"/><p>&nbsp</p><p align="center">OR</p>
<p align="center"><a href ="/users/login">Sign in</a></p></td></tr>

</table>

{% for village in village_detail %}
<ul>
<p>{{ village_detail.v_name }}</p>
<p>{{ village_detail.get_v_region_display }}</p>
<p>{{ village_detail.v_nearto }}</p>
<p>{{ village_detail.v_updated }}</p>
</ul>
{% endfor %}
{% endblock %}